{{- $deploymentsList := list }}
{{- if kindIs "map" .Values.deployments }}
  {{- range $key, $value := .Values.deployments }}
    {{- $deployment := deepCopy $value }}
    {{- if not (hasKey $deployment "name") }}
      {{- $_ := set $deployment "name" $key }}
    {{- end }}
    {{- $deploymentsList = append $deploymentsList $deployment }}
  {{- end }}
{{- else }}
  {{- $deploymentsList = .Values.deployments }}
{{- end }}
{{ range $deployment := $deploymentsList }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $deployment.name }}
  labels:
    {{- include "dagster.labels" $ | nindent 4 }}
    component: user-deployments
    deployment: {{ $deployment.name }}
  annotations:
    {{- if hasKey $deployment "service" }}
    {{- if hasKey $deployment.service "annotations" }}
    {{- range $key, $value := $deployment.service.annotations }}
    {{ $key }}: {{ $value | squote }}
    {{- end }}
    {{- end }}
    {{- end }}
spec:
  type: "ClusterIP"
  ports:
    - port: {{ $deployment.port }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "dagster.selectorLabels" $ | nindent 4 }}
    component: user-deployments
    deployment: {{ $deployment.name }}
---
{{ end }}
